package com.ao.model.message;

/**
 * Defines available server messages.
 */
public enum Message {
    DONT_SEE_ANYTHING,
    NPC_SWING,
    NPC_KILL_USER,
    BLOCKED_WITH_SHIELD_USER,
    BLOCKED_WITH_SHIELD_OTHER,
    USER_SWING,
    SAFE_MODE_ON,
    SAFE_MODE_OFF,
    RESUSCITATION_SAFE_OFF,
    RESUSCITATION_SAFE_ON,
    NOBILITY_LOST,
    CANT_USE_WHILE_MEDITATING,
    NPC_HIT_USER,
    USER_HIT_NPC,
    USER_ATTACKED_SWING,
    USER_HITTED_BY_USER,
    USER_HITTED_USER,
    WORK_REQUEST_TARGET,
    HAVE_KILLED_USER,
    USER_KILL,
    EARN_EXP,
    HOME,
    CANCEL_HOME,
    FINISH_HOME;
}
